apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: flux-test-app
  namespace: flux-test-app
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: flux-test-app
  chart:
    git: git@github.com:domingusj/flux-test
    path: charts/flux-test-app
    ref: production
  values:
    image: domingusj/flux-test-app:1.0.2
