apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-test-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flux-test-app
  template:
    metadata:
      labels:
        app: flux-test-app
    spec:
      containers:
        - image: "{{ .Values.image }}"
          name: flux-test-app
          ports:
            - containerPort: 8888
